# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "K8s Diver Blog"
description: > # this means to ignore newlines until "email:"
   A place for deep learning in Kubernetes networking, security, and observability.

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background.jpg"

name: 'Amgad Magdy'
author: 'Amgad Magdy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kdiver_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kdiver_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	github
#   url:	https://github.com/k8sdiver
#    desc:	Fork me on github
#    share_url:
#   share_title:
#   share_link:

